typography_spectrum: 0.9478963396683482
color:
  brandStrength: 0.4734723559389868
  lightness: 0.10948279637078026
  saturation: 0.23879843945910068
  rhythmicContrast: 0.25235237781935843
  brandColors:
    - '#F4F0DF'
    - '#005911'
    - '#0C981D'
    - '#201F1D'
    - '#D27717'
github: true
layout_spectrum: 0.11223124496832416
author:
  name: Patric Spohn
  email: patric.spohn@gmail.com
  url: 'http://volunteerprojectsceylon.org'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/72766cf7-5147-4e6e-8136-6911054af082.png
name: Volunteer Projects Ceylon Japan
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b2e69e4a-35ee-483d-a3eb-db6c4a9e837c.jpg
title: Volunteer Projects Ceylon Japan
content: []
description: >-
  We are an innovative and leading charity organisation devoted to providing 
  life-changing placements in  Sri Lanka for overseas volunteers.
purpose:
  - type: external
    url: 'http://volunteerprojectsceylon.org/apply.html'
    label: Apply now
  - type: contact
    url: 'mailto:patric.spohn@gmail.com'
    label: Contact us
